import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="p-0">
      <Head>
        <title className={""}>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={
          "flex flex-1 flex-col justify-center items-center min-h-screen p-1"
        }
      >
        <h1>
          Welcome to{" "}
          <a
            className="text-blue-600 decoration-0 hover: focus: active: underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>
      </main>

      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="h-4 ml-1">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
